version: "3.9"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/judge0
      - JUDGE0_URL=${JUDGE0_URL:-http://host.docker.internal:2358}
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo-data:
